version: "3.9"

services:
  eieimarketplace-slip-management:
    container_name: eiei-slip-management
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "7004:7004"
